services:
  npm:
    build: 
      context: .
      dockerfile: "dockerfiles/npm.dockerfile"
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ".:/app:cached"
    stdin_open: true
    tty: true
  section-14:
    build:
      context: .
      dockerfile: "dockerfiles/section-14.dockerfile"
    volumes:
      - ".:/app:cached"
    ports:
      - "3000:3000"
    env_file:
      - "env/mongo.env"