services:
  npm:
    build: 
      context: .
      dockerfile: "dockerfiles/npm.dockerfile"
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ".:/app:cached"
    stdin_open: true
    tty: true
  mongodb:
    build: 
      context: .
      dockerfile: dockerfiles/mongo.dockerfile
    env_file:
      - "env/mongo.env"
    network_mode: "host"
    ports:
    - "27017:27017"
    volumes:
      - mongo-data:/data/db
  section-14:
    build:
      context: .
      dockerfile: "dockerfiles/section-14.dockerfile"
    volumes:
      - ".:/app:cached"
    ports:
      - "3000:3000"
    env_file:
      - "env/mongo.env"
    network_mode: "host"
    depends_on:
      - mongodb
volumes:
  mongo-data: