services:
  section-11:
    build: .
    command: ["start"]
    ports:
      - 3000:3000
    volumes:
      - ".:/app"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=financier
      - POSTGRES_PASSWORD=asdffdsa
      - POSTGRES_DB=finance
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  npm:
    build: 
      context: .
      dockerfile: "npm.dockerfile"
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - "/home/lucas/projects/nodejs/section-11-Understanding-Sequelize:/app:cached"
    stdin_open: true
    tty: true
volumes:
  pgdata:
