services:
  section-11:
    build: .
    # npm is the entrypoint and start is the script that is being run from package.json
    command: ["start"]
    ports:
      - 3000:3000
    volumes:
      - ".:/app"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
