services:
  npm:
    build: 
      context: .
      dockerfile: "dockerfiles/npm.dockerfile"
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - "/home/lucas/projects/nodejs/section-14-Sessions-&-Cookies/00-starting-setup:/app:cached"
    stdin_open: true
    tty: true
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: maximilian
      MONGO_INITDB_ROOT_PASSWORD: asdffdsa
    ports:
    - "27017:27017"
    volumes:
      - mongo-data:/data/db
  section-14:
    build:
      context: .
      dockerfile: "dockerfiles/section-14.dockerfile"
    volumes:
      - "/home/lucas/projects/nodejs/section-14-Sessions-&-Cookies/00-starting-setup:/app:cached"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
volumes:
  mongo-data: